services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566:4566
    restart: always
    environment:
      LOCALSTACK_SERVICES: dynamodb

  pnotifier:
    depends_on:
      - localstack
    image: ${PRIVATE_DOCKER_REGISTRY}/pnotifier:${GIT_COMMIT}
    container_name: pnotifier
    restart: always
    environment:
      BOT_TOKEN: ${PNOTIFIER_BOT_TOKEN}
      DYNAMODB_ENDPOINT_URL: "http://localstack:4566"