services:
    localstack:
        image: localstack/localstack
        container_name: localstack
        ports: 
            - 4566:4566
        environment: 
            LOCALSTACK_SERVICES: dynamodb
    
    pnotifier:
        image: mcastellin/pnotifier
        build: .
        container_name: pnotifier
        restart: always
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            DYNAMODB_ENDPOINT_URL: "http://localstack:4566"